### ISSUE TITLE
question: integration testing with typeorm returning `undefined`

### ISSUE THREAD

**Issue by dnguneratne** [typeorm/typeorm-typedi-extensions#27] opened 2018-06-06 14:46 UTC
#### Issue
OrmRepository  injection works fine when running the server normally (can do a successful `getAll()` request). However, when I try to implement integration testing I get a `RepositoryNotFoundError`.

#### Packages involved
* Typedi
* Typeorm
* Typedi-typeorm-extensions
* mocha
* chai

##### bootstrap.ts
```js
import 'reflect-metadata';
import { useContainer as routingUseContainer, useExpressServer } from 'routing-controllers';
import { useContainer as ormUseContainer, getConnection } from 'typeorm';
import { Container } from 'typedi';
import { getDbConnection } from './db';

routingUseContainer(Container);
ormUseContainer(Container);

const controllerPath = path.join(config.appRootDir, '/dist/api/controllers/*.js');
const middlewarePath = path.join(config.appRootDir, '/dist/api/middleware/*.js');

async function bootstrap(): Promise<express.Express> {
  const app = express();

  useExpressServer(app, {
    routePrefix: '/api',
    controllers: [controllerPath],
    middlewares: [middlewarePath],
  });

  config.dbConnection = await getDbConnection();

  return app;
}
```

##### movie.service.ts
```js
import { Service } from 'typedi';
import { Repository } from 'typeorm';
import { OrmRepository } from 'typeorm-typedi-extensions';
import Movie from '../models/movie.model';

export interface IMovie {
  title: string;
  year: number;
}

@Service()
export default class MovieService {

  constructor(
    @OrmRepository(Movie)
    private movieRepository: Repository<Movie>,
  ) { }

  public async getAll(): Promise<IMovie[]> {
    return await this.movieRepository.find();
  }
}
```

##### movieService.test.ts
```js
import * as chai from 'chai';
import { Express } from 'express';
import 'mocha';
import { Container } from 'typedi';
import Movie from '../../api/models/movie.model';
import MovieService from '../../api/services/movie.service';
import bootstrap from '../../config/bootstrap';
import config from '../../config/config';

const expect = chai.expect;
let app: Express;

describe('MovieService', () => {
  before(async () => {
    app = await bootstrap();
  });

  after(async () => {
    return await config.dbConnection.close();
  });

  it('should create a new movie in the database', async () => {
    const movie = await new Movie();
    movie.title = 'test';
    movie.year = 2018;
    const movieService = await Container.get<MovieService>(MovieService);
    console.log(movieService);
    console.log('here');
  });
});
```
The test exists on `const movieService = await Container.get<MovieService>(MovieService);` with a `RepositoryNotFoundError`.  The `console.log` lines after this are not executed.

**Comment by mhaagens** [comment] 2019-03-29 09:31
Experiencing the same issue.

**Comment by alexeychikk** [comment] 2019-06-04 15:27
@dnguneratne It looks like you faced this issue https://github.com/typeorm/typeorm-typedi-extensions/issues/25

**Comment by NoNameProvided** [comment] 2021-01-15 20:35
Closing this, for now, if you still face this issue, please open a new one with **minimal, reproducible** example.

**Closed** 2021-01-15 20:35 UTC
Labels: type: question
