### ISSUE TITLE
injected repository is always undefined

### ISSUE THREAD

**Issue by babakyakhchali** [typeorm/typeorm-typedi-extensions#25] opened 2018-04-17 19:40 UTC
Hi
I'm trying to inject some repository into a routing-controllers controller like this:

```typescript
import { Param, Body, Get, Post, Put, Delete, JsonController } from "routing-controllers";
import { InjectRepository } from "typeorm-typedi-extensions";
import { Repository } from "typeorm";
import { User } from "../entities/User";
import { Service } from "typedi";

@JsonController('/users')
@Service()
export class UserController {

    @InjectRepository(User)
    private repository: Repository<User>;

    @Get("/")
    getAll() {
        return this.repository.find();
    }
}
```

but this.repository is always undefined!

this is my app entry main.ts file:
```typescript
import "reflect-metadata";
import { createConnection, useContainer} from 'typeorm';
import { createExpressServer } from "routing-controllers";
import { UserController } from "./src/controllers/UserController";

import { Container } from 'typedi';

useContainer(Container);
createConnection().then(async connection => {
}).catch(error => console.log(error));

const app = createExpressServer({
    controllers: [UserController] // we specify controllers we want to use
 });
 app.listen(3000);
```
all entities are created and express is working.

**Comment by ReganHe** [comment] 2018-04-19 06:58
我使用0.1.1版本也有一样的问题，经分析，这个版本没有InjectRepository，可使用OrmRepository。

**Comment by nodew** [comment] 2018-06-03 05:51
the same issue as @babakyakhchali

**Comment by lenmerkel** [comment] 2018-10-09 22:42
I have a very similar setup to **@babakyakhchali** and see exactly the same behavior. I can step into **useContainer** and **@InjectRepository**, both appear to execute normally (i.e. no Errors thrown). However, the property is never initialized (i.e. it is undefined).

My **npm** dependencies and installed packages are:
```json
  "devDependencies": {
    "@types/node": "^10.11.6",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.1"
  },
  "dependencies": {
    "class-transformer": "^0.1.9",
    "graphql-yoga": "^1.16.2",
    "mysql": "^2.16.0",
    "reflect-metadata": "^0.1.12",
    "type-graphql": "^0.14.0",
    "typedi": "^0.8.0",
    "typeorm": "^0.2.7",
    "typeorm-typedi-extensions": "^0.2.1"
  }
```

**Comment by feimosi** [comment] 2018-11-19 15:43
Doesn't work for me either (I've tried `InjectManager` and `InjectRepository`).

**Comment by nikomon** [comment] 2019-05-07 10:06
Same issue

**Comment by alexeychikk** [comment] 2019-06-04 15:20
@babakyakhchali @nodew @feimosi  @nikomon 
Guys, has someone managed to find the source of the issue?

**Comment by feimosi** [comment] 2019-06-04 16:14
I don't already remember, it's been a very long time ago. I have the latest version of each package and everything works fine. Maybe make sure you invoke `useContainer` from both packages separately (`typeorm` and `routing-controllers`).

**Comment by alexeychikk** [comment] 2019-06-04 17:26
@feimosi I found the source of the issue. I am trying to inject repository into repository. And for some reason this is not working. When I try to inject the same repository into service - it does work.

**Comment by peterbabic** [comment] 2019-07-05 08:09
For me, using type-grapghql the difference was in 

```js
const schema = await buildSchema({
    resolvers: [UserResolver],
    // need to register the container here as well
    container: Container
})
```

just using `useContainer(Container)` from `typeorm` is not enough

**Comment by 73cn0109y** [comment] 2019-07-05 15:20
As @peterbabic suggested, I also had to do something like this;

```JS
private async buildSchema() {
    useContainer(Container);
    
    return await buildSchema({
        resolvers: [ UserResolver ],
        emitSchemaFile: true,
        container: Container,
    });
}
```

**Comment by nbaua** [comment] 2019-07-27 16:22
I have following code (some lines removed for brevity)

`
@Injectable()
export class ProductsService {
  constructor(
    @InjectRepository(ProductRepository)
    private repo: ProductRepository,
  ) {
    console.log('inside service');
  }
......
  .......
  async getProductById(id: number): Promise<Product> {
    console.log(this.repo);

    const matchingProduct = await this.repo.findOne(id);
    if (!matchingProduct) {
      throw new NotFoundException(`Product Not Found!`);
    }
    return matchingProduct;
  }
}
`

**I get the following error at run-time.** There are no compile-time issues, server starts/runs perfectly fine, until we hit the end-point because **ProductRepository** is always undefined.

> [Nest] 4708   - 07/27/2019, 9:40 PM   [ExceptionsHandler] Cannot read property 'findOne' of undefined +205ms
> TypeError: Cannot read property 'findOne' of undefined
>     at ProductRepository.Repository.findOne (D:\Projects\BestDealsOnline\src\repository\Repository.ts:296:29)
>     at ProductsService.getProductById (D:\Projects\BestDealsOnline\src\products\products.service.ts:35:45)
>     at ProductsController.getProductById (D:\Projects\BestDealsOnline\src\products\products.controller.ts:34:33)
 


This code was working days before.
Please suggest how this can be resolved.

**Comment by shahzaib-sheikh** [comment] 2020-02-18 14:04
I was facing the same issue. I turned out to be a circular dependency issue.

**Comment by arslanmughal5566** [comment] 2020-04-05 13:28
> 
> 
> I was facing the same issue. It turned out to be a circular dependency issue.

Can you please show example how you fix that ? i'm also facing same issue as @nbaua  i have also tried forwardRef but no luck :-(

**Comment by shahzaib-sheikh** [comment] 2020-04-05 20:37
I just removed the code which was causing circular dependency. 
To check for circular dependency start with the class which is returned undefined from Typedi, In that class check for files which this file imports. you will get to the code which is causing circular dependency. Also setup debugger if you haven't and put a breakpoint on the class which is undefined. when the code stops at breakpoint look into the stack trace you'll definitely get to that code.

**Comment by arslanmughal5566** [comment] 2020-04-08 09:12
So my solution was to replace this 

```
export class UserService {
    constructor(
         private userRepository: UserRepository;
         private authRepository: AuthRepository;
     ) {  }
}
```
with this using `Connection` from typeorm
```
export class UserService {
    private userRepository: UserRepository;
    private authRepository: AuthRepository;
    constructor(
        private readonly connection: Connection
    ) {
        this.userRepository = this.connection.getCustomRepository(UserRepository);
        this.authRepository = this.connection.getCustomRepository(AuthRepository);
    }
}
```

Now it work like charm :)

**Comment by creepinson** [comment] 2020-09-23 18:36
same issue, i tried injectconnection AND injectrepository but both didnt work and the repo is undefined.

**Comment by JipSterk** [comment] 2021-01-12 23:00
i use a `resolver` from `type-graphql` which import code like the snippet below when the object instantiated by `type-di` with a inject. 

```ts
@Inject(() => UserService)
```

when kafka consumer has called his eachMessage. userRepository hasn't been instantiated yet

```ts
@Service()
export class UserService {
  @InjectRepository(User)
  private readonly userRepository: Repository<User>;

  constructor() {
    this.setupUserConsumer();
  }

  async setupUserConsumer(): Promise<void> {
    const userConsumer = kafka.consumer({ groupId: "user-group" });
    await userConsumer.connect();
    await userConsumer.subscribe({
      topic: "create-user",
      fromBeginning: true,
    });
    await userConsumer.run({
      eachMessage: this.createUser,
    });
  }

  private async createUser({ message }: EachMessagePayload): Promise<void> {
    const { user } = JSON.parse(
      message.value.toString()
    ) as CreateUserMessage;

    await this.userRepository.save({ //<-- here userRepository is undefined 
      id: user.id,
    });
  }
}
```

**Comment by NoNameProvided** [comment] 2021-01-15 17:54
There are tons of unrelated issues here. I am closing this, if you are still facing issues, please open a new issue with a **minimal, reproducible** example. Thanks!

**Closed by NoNameProvided** 2021-01-15 17:54 UTC
Labels: type: question
